/* PromptCard — shared UI strings (en/tr) */
"use strict";
if (!globalThis.__pcMessagesLoaded) {
  globalThis.__pcMessagesLoaded = true;

  globalThis.PC_DEFAULT_LANG = "en";

  globalThis.PC_MESSAGES = {
    en: {
      menuTitle: "🎴 PromptCard: Generate AI prompt for this image",
      chip: "🎴 Prompt",
      close: "Close",
      copy: "Copy",
      copied: "Copied ✓",
      redo: "↻ Redo",
      loading: "Analyzing image…",
      analyzeFail: "Analysis failed",
      settings: "⚙ Settings",
      scanning: "Scanning page…",
      unsupported: "This page is not supported (http/https pages only).",
      noImages: "No analyzable images found on this page.",
      foundImages: "{n} images found — click one to generate a prompt.",
      injectFail: "Could not inject the content script into this page.",
      fetchFail: "Could not download the image: {msg}",
      noteNoKey: "No API key — the built-in local analysis was used. Add an OpenAI-compatible key in the extension options for richer prompts.",
      noteAiFail: "AI request failed ({msg}) — local analysis was used.",
      emptyModel: "The model returned an empty response",
      optTitle: "PromptCard Settings",
      langLabel: "Language",
      apiBaseLabel: "API address (OpenAI-compatible)",
      apiKeyLabel: "API key",
      modelLabel: "Model",
      save: "Save",
      saved: "Saved ✓",
      optHint: "The API key is optional. Without a key, the built-in local analysis engine runs fully offline. Add an OpenAI-compatible key + model and prompts are generated by a vision model.",
    },
    tr: {
      menuTitle: "🎴 PromptCard: Bu görsel için AI prompt üret",
      chip: "🎴 Prompt",
      close: "Kapat",
      copy: "Kopyala",
      copied: "Kopyalandı ✓",
      redo: "↻ Yeniden",
      loading: "Görsel analiz ediliyor…",
      analyzeFail: "Analiz başarısız oldu",
      settings: "⚙ Ayarlar",
      scanning: "Sayfa taranıyor…",
      unsupported: "Bu sayfa desteklenmiyor (yalnızca http/https sayfaları).",
      noImages: "Sayfada analiz edilebilir görsel bulunamadı.",
      foundImages: "{n} görsel bulundu — prompt üretmek için birine tıkla.",
      injectFail: "Sayfaya content script enjekte edilemedi.",
      fetchFail: "Görsel indirilemedi: {msg}",
      noteNoKey: "API anahtarı yok — yerleşik yerel analiz kullanıldı. Daha zengin promptlar için eklenti ayarlarından OpenAI uyumlu bir anahtar ekleyebilirsin.",
      noteAiFail: "AI isteği başarısız oldu ({msg}) — yerel analiz kullanıldı.",
      emptyModel: "Modelden boş yanıt geldi",
      optTitle: "PromptCard Ayarları",
      langLabel: "Dil",
      apiBaseLabel: "API adresi (OpenAI uyumlu)",
      apiKeyLabel: "API anahtarı",
      modelLabel: "Model",
      save: "Kaydet",
      saved: "Kaydedildi ✓",
      optHint: "API anahtarı opsiyoneldir. Anahtar yoksa yerleşik yerel analiz motoru tamamen çevrimdışı çalışır. OpenAI uyumlu bir anahtar + model eklersen prompt'lar vision modeli tarafından üretilir.",
    },
  };

  globalThis.pcT = function (lang, key, vars) {
    const d = PC_MESSAGES[lang] || PC_MESSAGES.en;
    let s = (d[key] != null) ? d[key] : ((PC_MESSAGES.en[key] != null) ? PC_MESSAGES.en[key] : key);
    if (vars) { for (const k in vars) s = s.split("{" + k + "}").join(vars[k]); }
    return s;
  };

  globalThis.pcGetLang = async function () {
    try {
      const s = await browser.storage.sync.get({ lang: PC_DEFAULT_LANG });
      return (s && s.lang) || PC_DEFAULT_LANG;
    } catch (e) { return PC_DEFAULT_LANG; }
  };
}
